paths:

  /api/products/:

    get:
      summary: Obtiene una lista de productos en un arreglo 
      tags:
        - Products
      responses:
        '200':
          description: Se obtuvo la lista de productos satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '400':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $type: string
                example: Error al consultar los productos

    post:
      summary: Registra un nuevo producto en la base de datos
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses:
        '201':
          description: Producto agregado
          content:
            application/json:
              $type: string
              example: Producto agregado
        '401':
          description: Error
          content:
            application/json:
              $type: string
              example: Unauthorized
        '400':
          description: Error en el registro del producto
          content:
            application/json:
              schema:
                $type: string
                example: Error en el registro del producto

  /api/products/{pid}:

    get:
      summary: Obtiene un producto especificado por su identificador
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Parametro para indicar el identificador de producto
        schema:
          $type: String
      responses:
        '200':
          description: Se obtuvo el producto satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '400':
          description: Error al consultar el producto
          content:
            application/json:
              schema:
                $type: string
                example: Error al consultar el producto
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $type: string
                example: Producto no encontrado

    put:
      summary: Actualiza el producto especificado por identificador
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Identificador del producto que se desea actualizar
      requestBodies:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        '200':
          description: Se actualizo el producto satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '400':
          description: Error al consultar el producto
          content:
            application/json:
              schema:
                $type: string
                example: Error al consultar el producto

    delete:
      summary: Borra el producto de la base de datos
      tags:
        - Products
      responses:
        '200':
          description: El producto se borro satisfctoriamente
          content: 
            text/plain:
              schema:
                $type: string
                example: Producto borrado
        '400':
          description: Error al borrar el producto
          content:
            text/plain:
              $type: string
              example: Error al borrar el producto

components:

  schemas:

    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Identificador autogenerado por MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo identificador interno del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: boolean
          description: Indica existencia en almacen
        stock:
          type: Number
          description: Cantidad de productos en almacen
        category:
          type: String
          description: Define la categoria a la que pertenece el producto
        thumbnail:
          type: Array
          description: Arreglo con las direcciones de las imagenes del producto
        __v:
          type: number
          description: Numero autogenerdo por MongoDB      
      example:
        _id: ObjectId('j8e6fie3afx7pro4jbkf2')
        title: Botella 500ml
        description: Botella con capacidad de 500ml
        code: BOT500
        price:  7
        status: true
        stock:  45 
        category: Botella
        thumbnail: []
        __v: 0

    Products:
      type: object
      properties: 
        docs:
          type: array
          items:
            $ref: '#/components/schemas/Product'

        totalDocs:
          type: number
        offset:
          type: number
        limit:
          type: number
        totalPages:
          type: number
        page:
          type: number
        pagingCounter:
          type: number
        hasPrevPage:
          type: boolean
        hasNextPage:
          type: boolean
        prevPage:
          type: number
        nextPage:
          type: number
  
  requestBodies:

    createProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
          example: Product Test
        description:  
          type: String
          description: Descripcion del producto
          example: Product Test Description
        code:
          type: String
          description: Codigo identificador unico
          example: PTC1 
        price:
          type: Number
          description: Precio del producto
          example: 10
        stock:
          type: Number
          description: Numero de ejemplares en existencia del producto
          example: 100
        category:
          type: String
          description: Categoria del producto
          example: Product Test Category

    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:  
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo identificador unico 
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Numero de ejemplares en existencia del producto
        category:
          type: String
          description: Categoria del producto